### ISSUE TITLE
[BUG] npm not compatible with pinned Node version

### ISSUE THREAD

**Issue by Milkshak3s** [KCarretto/paragon#313]
Need to bump Node version, as npm no longer supports this.
Maybe consider bumping to `16.13.2 LTS` ?

```
 > [ 5/10] RUN npm install -g eslint:
#8 0.423 npm does not support Node.js v10.24.0
#8 0.424 Yo
[2022-01-21T16:48:32.779Z] u should probably upgrade to a newer version of node as we
#8 0.424 can't make any promises that npm will work with this version.
#8 0.424 You can find the latest version at https://nodejs.org/
#8 0.441 /usr/local/lib/node_modules/npm/lib/npm.js:32
#8 0.441   #unloaded = false
#8 0.441   ^
#8 0.441 
#8 0.441 SyntaxError: Invalid or unexpected token
#8 0.441     at Module._compile (internal/modules/cjs/loader.js:723:23)
#8 0.441     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
#8 0.441     at Module.load (internal/modules/cjs/loader.js:653:32)
#8 0.441     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
#8 0.441     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
#8 0.441     at Module.require (internal/modules/cjs/loader.js:692:17)
#8 0.441     at require (internal/modules/cjs/helpers.js:25:18)
#8 0.441     at module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:22:15)
#8 0.441     at Object.<anonymous> (/usr/local/lib/node_modules/npm
[2022-01-21T16:48:32.779Z] /bin/npm-cli.js:2:25)
#8 0.441     at Module._compile (internal/modules/cjs/loader.js:778:30)
```

**Comment by Milkshak3s** [comment]
Ehhh I may have misunderstood the error here

**Comment by Milkshak3s** [comment]
I was correct here :D
